import type { ArtifactDocument, ArtifactPackage } from './model.ts';

export const sampleDocument: ArtifactDocument = {
  artifact: {
    id: 'answer-interface-01',
    kind: 'decision-brief',
    title: 'AI 回答正在越过文本的吸收上限',
    question: '怎样把模型的大信息量，变成人能在一分钟内理解、判断和反馈的界面？',
    summary:
      '不要继续优化长文本的排版。让模型输出稳定的数据协议，由模板负责信息架构和交互，再把人的圈注变成结构化上下文送回模型。',
    generatedAt: '2026-07-14T09:00:00+08:00',
    tags: ['generative UI', 'JSON protocol', 'annotation loop'],
  },
  metrics: [
    {
      id: 'scan-time',
      label: '首轮扫读',
      value: 42,
      unit: ' 秒',
      delta: '比长文本快 61%',
      trend: [108, 96, 81, 68, 55, 42],
    },
    {
      id: 'claims',
      label: '可见判断',
      value: 18,
      unit: ' 条',
      delta: '全部可定位',
      trend: [5, 8, 10, 12, 15, 18],
    },
    {
      id: 'coverage',
      label: '证据覆盖',
      value: 83,
      unit: '%',
      delta: '15 / 18 有来源',
      trend: [43, 52, 58, 65, 76, 83],
    },
    {
      id: 'open-decisions',
      label: '待定问题',
      value: 3,
      unit: ' 个',
      delta: '已经显式暴露',
      trend: [9, 8, 6, 5, 4, 3],
    },
  ],
  insights: [
    {
      id: 'text-ceiling',
      label: '问题',
      title: '瓶颈已经从生成速度转向理解速度',
      body: '模型能在几秒内给出上千字，但读者仍按线性顺序吸收。更多 token 不再等于更多有效信息。',
      confidence: 0.94,
      evidence: ['founder-note', 'answer-sample'],
      tone: 'signal',
    },
    {
      id: 'protocol-first',
      label: '架构判断',
      title: '模板协议比每次生成完整网页更稳定',
      body: 'AI 优先生成受约束 JSON；模板掌握密度、层级、响应式和可访问性。只有模板缺失时才进入代码生成。',
      confidence: 0.88,
      evidence: ['answer-sample', 'renderer-spike'],
      tone: 'decision',
    },
    {
      id: 'annotation-context',
      label: '交互判断',
      title: '圈注应返回语义路径，而不只是截图坐标',
      body: '用户点到的是“证据覆盖率”或“第二条判断”。反馈 payload 需要同时携带 JSON Pointer、可见摘录、模板和评论。',
      confidence: 0.91,
      evidence: ['founder-note', 'renderer-spike'],
      tone: 'decision',
    },
    {
      id: 'runtime-risk',
      label: '风险',
      title: '任意依赖与任意代码必须被隔离',
      body: '“开放”不等于在宿主页面直接执行未知脚本。模板、依赖、网络和数据权限需要明确的 sandbox 边界。',
      confidence: 0.86,
      evidence: ['security-review'],
      tone: 'risk',
    },
  ],
  sources: [
    {
      id: 'founder-note',
      label: '创始人原始想法',
      detail: '关于文本吸收上限、模板 JSON 输入和圈注交互的口述 brief。',
      kind: 'brief',
    },
    {
      id: 'answer-sample',
      label: '12 份长回答样本',
      detail: '每份 1,200–3,400 字，包含结论、证据、步骤和未决问题。',
      kind: 'dataset',
    },
    {
      id: 'renderer-spike',
      label: '浏览器渲染 spike',
      detail: '同一份 JSON 同时驱动三种信息结构，并保留稳定语义路径。',
      kind: 'prototype',
    },
    {
      id: 'security-review',
      label: '运行时威胁清单',
      detail: '第三方脚本、网络访问、凭据泄露与宿主 DOM 越权。',
      kind: 'review',
    },
  ],
  timeline: [
    {
      id: 'intent',
      when: '00:00',
      title: '识别回答意图',
      detail: '模型选择 artifact kind 与模板能力。',
      state: 'complete',
    },
    {
      id: 'stream',
      when: '00:02',
      title: '流式生成 JSON',
      detail: '字段到达后，局部模块立即渲染。',
      state: 'complete',
    },
    {
      id: 'compose',
      when: '00:05',
      title: '组合高密度界面',
      detail: '模板把判断、证据、指标与行动放进同一视野。',
      state: 'current',
    },
    {
      id: 'annotate',
      when: '00:42',
      title: '用户圈选并评论',
      detail: '界面捕获 JSON Pointer、摘录和视觉区域。',
      state: 'next',
    },
    {
      id: 'patch',
      when: '00:46',
      title: 'AI 定点修改',
      detail: '模型只重写目标数据或模板片段。',
      state: 'next',
    },
  ],
  actions: [
    {
      id: 'freeze-schema',
      title: '冻结 Artifact Package v0.1',
      detail: '先覆盖判断、指标、证据、过程和行动五类通用信息。',
      owner: 'Protocol',
      state: 'ready',
    },
    {
      id: 'test-templates',
      title: '用同一 JSON 验证三种模板',
      detail: '判断信息密度是否来自结构，而不是装饰。',
      owner: 'Renderer',
      state: 'ready',
    },
    {
      id: 'sandbox',
      title: '定义自定义模板 sandbox',
      detail: '明确脚本、依赖、网络和宿主通信能力。',
      owner: 'Runtime',
      state: 'blocked',
    },
  ],
};

export const samplePackage: ArtifactPackage = {
  artifactVersion: '0.1',
  id: 'open-artifact-answer-interface-01',
  revision: 1,
  renderer: {
    kind: 'template',
    id: 'decision-brief',
    version: '0.1.0',
  },
  inputSchema: './docs/spec/artifact-package.v0.1.schema.json#/$defs/decisionBriefData',
  capabilities: {
    network: 'none',
    code: 'trusted-components',
  },
  provenance: {
    generator: 'prototype-sample',
    createdAt: '2026-07-14T09:00:00+08:00',
  },
  editPolicy: 'patchable',
  data: sampleDocument,
};
